// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3jkdAKxNoHZpg5SjZnK2WVb2qb0DXams',
    appId: '1:866694795181:web:69836bfd26d13ba4fddb24',
    messagingSenderId: '866694795181',
    projectId: 'electronic-qiu-guidance-system',
    authDomain: 'electronic-qiu-guidance-system.firebaseapp.com',
    storageBucket: 'electronic-qiu-guidance-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmD26_d74SlcPIqxxjvRT5doU0XXcPGkI',
    appId: '1:866694795181:android:2c67bdf4fa55bf7afddb24',
    messagingSenderId: '866694795181',
    projectId: 'electronic-qiu-guidance-system',
    storageBucket: 'electronic-qiu-guidance-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Es_LngZ_5Dc_94GfXI5ZUf6o9xBn084',
    appId: '1:866694795181:ios:66a33a5781d837d8fddb24',
    messagingSenderId: '866694795181',
    projectId: 'electronic-qiu-guidance-system',
    storageBucket: 'electronic-qiu-guidance-system.appspot.com',
    iosBundleId: 'com.example.qiuDigitalGuidance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Es_LngZ_5Dc_94GfXI5ZUf6o9xBn084',
    appId: '1:866694795181:ios:f4bdf41c38517d70fddb24',
    messagingSenderId: '866694795181',
    projectId: 'electronic-qiu-guidance-system',
    storageBucket: 'electronic-qiu-guidance-system.appspot.com',
    iosBundleId: 'com.example.qiuDigitalGuidance.RunnerTests',
  );
}
